import{Router}from'express';import rateLimit from'express-rate-limit';import{z}from'zod';import{asyncHandler,ok}from'./utils.js';import{auth,permit,upload,validate}from'./middleware.js';import{agents,authController,createLead,createSimple,dashboard,deleteSimple,leadList,leadPatch,listModel,properties,submissions}from'./controllers.js';import{contactSchema,inquirySchema,loginSchema,newsletterSchema,propertySchema,submissionSchema,viewingSchema}from'./validators.js';import{prisma}from'./config.js';
const r=Router(),slow=rateLimit({windowMs:15*60*1000,limit:20,standardHeaders:true,legacyHeaders:false,message:{success:false,message:'Too many requests. Please try again later.'}});r.get('/health',(req,res)=>ok(res,{status:'healthy',timestamp:new Date().toISOString()}));
r.post('/auth/login',slow,validate(loginSchema),asyncHandler(authController.login));r.get('/auth/me',auth,asyncHandler(authController.me));
r.get('/properties',asyncHandler((q,s)=>properties.list(q,s,false)));r.get('/properties/:id',asyncHandler((q,s)=>properties.one(q,s,false)));r.get('/admin/properties',auth,asyncHandler((q,s)=>properties.list(q,s,true)));r.get('/admin/properties/:id',auth,asyncHandler((q,s)=>properties.one(q,s,true)));r.post('/properties',auth,validate(propertySchema),asyncHandler(properties.create));r.put('/properties/:id',auth,validate(propertySchema),asyncHandler(properties.update));r.patch('/properties/:id',auth,asyncHandler(properties.patch));r.delete('/properties/:id',auth,permit('SUPER_ADMIN','ADMIN'),asyncHandler(properties.remove));r.post('/properties/:id/images',auth,upload.array('images',12),asyncHandler(properties.upload));r.delete('/properties/:id/images/:imageId',auth,asyncHandler(properties.imageDelete));r.patch('/properties/:id/images/:imageId/primary',auth,asyncHandler(properties.primary));
const publicLists=[['categories','category'],['locations','location'],['amenities','amenity'],['testimonials','testimonial']];for(const[name,model]of publicLists){r.get('/'+name,asyncHandler((q,s)=>listModel(q,s,model,model==='amenity'?{}:{active:true})));r.post('/'+name,auth,asyncHandler((q,s)=>createSimple(q,s,model)));r.delete(`/${name}/:id`,auth,asyncHandler((q,s)=>deleteSimple(q,s,model)))}r.get('/agents',asyncHandler((q,s)=>listModel(q,s,'agent',{active:true})));r.get('/agents/:id',asyncHandler(agents.one));r.post('/agents',auth,asyncHandler((q,s)=>createSimple(q,s,'agent')));r.delete('/agents/:id',auth,asyncHandler((q,s)=>deleteSimple(q,s,'agent')));
const leads=[['inquiries','inquiry',inquirySchema],['viewing-requests','viewingRequest',viewingSchema],['contact','contactMessage',contactSchema]];for(const[name,model,schema]of leads){r.post('/'+name,slow,validate(schema),asyncHandler((q,s)=>createLead(q,s,model)));r.get('/'+name,auth,asyncHandler((q,s)=>leadList(q,s,model)));r.patch(`/${name}/:id`,auth,asyncHandler((q,s)=>leadPatch(q,s,model)));r.delete(`/${name}/:id`,auth,asyncHandler(async(q,s)=>{await prisma[model].delete({where:{id:q.params.id}});ok(s,null,'Deleted')}))}
r.post('/newsletter',slow,validate(newsletterSchema),asyncHandler(async(q,s)=>ok(s,await prisma.newsletterSubscriber.upsert({where:{email:q.body.email},update:{active:true},create:q.body}),'Subscribed',201)));r.get('/newsletter',auth,asyncHandler((q,s)=>listModel(q,s,'newsletterSubscriber')));r.delete('/newsletter/:id',auth,asyncHandler((q,s)=>deleteSimple(q,s,'newsletterSubscriber')));
r.post('/property-submissions',slow,upload.array('images',10),(req,res,next)=>{try{req.body=submissionSchema.parse(req.body);next()}catch(e){next(e)}},asyncHandler(submissions.create));r.get('/property-submissions',auth,asyncHandler(submissions.list));r.post('/property-submissions/:id/approve',auth,asyncHandler(submissions.approve));r.post('/property-submissions/:id/reject',auth,asyncHandler(submissions.reject));
r.get('/dashboard',auth,asyncHandler(dashboard));r.get('/admin-users',auth,permit('SUPER_ADMIN'),asyncHandler((q,s)=>listModel(q,s,'adminUser')));r.post('/admin-users',auth,permit('SUPER_ADMIN'),asyncHandler((q,s)=>createSimple(q,s,'adminUser')));r.delete('/admin-users/:id',auth,permit('SUPER_ADMIN'),asyncHandler((q,s)=>deleteSimple(q,s,'adminUser')));
r.get('/settings',asyncHandler(async(q,s)=>ok(s,await prisma.siteSetting.findUnique({where:{id:'main'}}))));r.put('/settings',auth,asyncHandler(async(q,s)=>ok(s,await prisma.siteSetting.upsert({where:{id:'main'},update:q.body,create:{id:'main',...q.body}}),'Settings saved')));r.get('/homepage-content',asyncHandler(async(q,s)=>ok(s,await prisma.homepageSection.findUnique({where:{id:'main'}}))));r.put('/homepage-content',auth,asyncHandler(async(q,s)=>ok(s,await prisma.homepageSection.upsert({where:{id:'main'},update:q.body,create:{id:'main',heroHeading:q.body.heroHeading||'Find a Place You’ll Love to Live',heroDescription:q.body.heroDescription||'',...q.body}}),'Content saved')));export default r;
